In [2]:
import numpy as np
a = np.full((5,5),0)
a[0,:] = 1
a[-1,:] = 1
a[:,0] = 1
a[:,-1] = 1
a[len(a)//2,len(a)//2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [23]:
b = np.arange(1,31).reshape((6,5))
# b[2:4,0:2]
b[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [26]:
c = np.arange(5)
c

array([0, 1, 2, 3])